### PR TITLE
feat: added MAKEFLAGS checking

### PR DESCRIPTION
**Pull request by Nikhil-Nunna**
## Description

This PR adds a feature that allows developers to call the
"flag-check" option which then checks any arguments passed into
makefile against variables in the makefile to ensure that the "MAKEFLAGS"
passed in are valid.

### CODE REVIEW

**Review by cdrickett — APPROVED** [review]

**Comment by stoksc** [comment]
can we close this? been getting pinged about it for almost a year in my slack github notifs 😆

**Comment by stoksc** [comment]
or, alternatively, if you still are interested, maybe reassign @ioga  or whoever he recommends

**Comment by ioga** [comment]
if we'd like to merge this, we need to reformat the python code according to the mypy/flake8 configuration from the main repo.

**Comment by Nikhil-Nunna** [comment]
Yeah if it's too big of a change I'll go ahead and just close it.

**Pull request closed without merging**
