### PR TITLE
Add ssh-rsa hostkey workaround

### PR DESCRIPTION
**Pull request by dannysauer**
## Description

Inspired by https://github.com/hashicorp/packer-plugin-ansible/issues/69#issuecomment-1342585096, except our version of packer doesn't seem to yet support the `ansible_ssh_extra_args` parameter (at least, it fails when I use it).  The first two args are for rsa hostkeys, and the "identities only" is what the default value is.

We should probably upgrade packer and use the ssh_extra_args instead.  Someday.

https://developer.hashicorp.com/packer/plugins/provisioners/ansible/ansible#ansible_ssh_extra_args

## Checklist

- [x] Bump VERSION to make the pushed images are tagged with the right version.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by rb-determined-ai** [comment]
> Bump VERSION to make the pushed images are tagged with the right version

What is the risk involved with not bumping the version?  This doesn't seem like it should be changing the content of the images.

**Comment by dannysauer** [comment]
I just checked it because it wasn't applicable.  I'm a fan of checklists being complete.

**Comment by rb-determined-ai** [comment]
got it

**Comment by mpkouznetsov** [comment]
I am guessing this can be closed now that it is part of another PR that has been merged.

**Comment by dannysauer** [comment]
This is in #175. Closing.

**Pull request closed without merging**
