### PR TITLE
    Subject: Add OpenMPI support to NVIDIA GPU targets

### PR DESCRIPTION
**Pull request by cdrickett**
Description:

    This mod adds OpenMPI support to the targets for NVIDIA gpus, similar
    to what was done for the CPU images. OpenMPI can now be built into the
    base image using the USE_MPI=1 option, such as:
```
    $> make USE_MPI="1" build-tf24-gpu
```

    After building this image and converting to Singularity, the image was
    tested on an IB cluster using the OSU benchmarks to verify
    performance.
```
    $ srun --mpi=pmi2 -p gpuNodes -n 2 --ntasks-per-node=1 singularity
    exec --bind /lus /lus/scratch/username/detAI-cuda-11.1-torch-1.9-tf-2.4-gpu-mpi.sif ./osu-micro-benchmarks-5.6.2/mpi/one-sided/osu_get_bw
    1                       2.06
    2                       4.21
    4                       8.41
    8                      16.83
    16                     33.77
    32                     66.42
    64                    128.51
    128                   246.12
    256                   493.93
    512                  1013.98
    1024                 1871.85
    2048                 3200.73
    4096                 4763.36
    8192                 6239.26
    16384                8293.17
    32768               11066.21
    65536               11517.27
    131072              11574.10
    262144              11581.30
    524288              11165.66
    1048576             10911.13
    2097152             10533.11
    4194304              9755.71
```
    Also tested with the TF2 MNIST test on 2 nodes using 8 gpus per node:
```
    $ srun --mpi=pmi2 -n 16 --ntasks-per-node=8 singularity exec --nv --bind /lus /lus/scratch/username/detAI-cuda-11.1-torch-1.9-tf-2.4-gpu-mpi.sif python /lus/scratch/username/tensorflow2_mnist.py >& log-gpu.txt
```
    In the log-gpu.txt file I verified that hvd.init() showed the correct
    MPI world size and ranks:
```
    $ grep "hvd\.size" log-gpu.txt
    hvd.local_rank(): 6, hvd.rank(): 6, hvd.size(): 16
    hvd.local_rank(): 2, hvd.rank(): 2, hvd.size(): 16
    hvd.local_rank(): 4, hvd.rank(): 12, hvd.size(): 16
    hvd.local_rank(): 6, hvd.rank(): 14, hvd.size(): 16
    hvd.local_rank(): 2, hvd.rank(): 10, hvd.size(): 16
    hvd.local_rank(): 4, hvd.rank(): 4, hvd.size(): 16
    hvd.local_rank(): 3, hvd.rank(): 11, hvd.size(): 16
    hvd.local_rank(): 0, hvd.rank(): 0, hvd.size(): 16
    hvd.local_rank(): 7, hvd.rank(): 7, hvd.size(): 16
    hvd.local_rank(): 0, hvd.rank(): 8, hvd.size(): 16
    hvd.local_rank(): 7, hvd.rank(): 15, hvd.size(): 16
    hvd.local_rank(): 3, hvd.rank(): 3, hvd.size(): 16
    hvd.local_rank(): 1, hvd.rank(): 9, hvd.size(): 16
    hvd.local_rank(): 5, hvd.rank(): 5, hvd.size(): 16
    hvd.local_rank(): 5, hvd.rank(): 13, hvd.size(): 16
    hvd.local_rank(): 1, hvd.rank(): 1, hvd.size(): 16
```
    The tensorflow2_mnist.py test completed as expected:
```
    $ tail log-gpu.txt
    Step #580          Loss: 0.049359
    Step #580          Loss: 0.064985
    Step #590          Loss: 0.040959
    Step #590          Loss: 0.183963
    Step #600          Loss: 0.039476
    Step #600          Loss: 0.103435
    Step #610          Loss: 0.049162
    Step #610          Loss: 0.048544
    Step #620          Loss: 0.084336
    Step #620          Loss: 0.046733
```
    Note: I was not able to build the tf1-gpu and tf2-gpu images because I
    encountered an error in the install.apex.sh similar to:
```
    ERROR: Command errored out with exit status 1: /opt/conda/bin/python
    -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] =
    '"'"'/tmp/pip-req-build-ao9mgp98/setup.py'"'"';
    __file__='"'"'/tmp/pip-req-build-ao9mgp98/setup.py'"'"';f =
    getattr(tokenize, '"'"'open'"'"', open)(__file__) if
    os.path.exists(__file__) else io.StringIO('"'"'from setuptools import
    setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"',
    '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
    --cpp_ext --cuda_ext install --record
    /tmp/pip-record-4l_4so8t/install-record.txt
    --single-version-externally-managed --compile --install-headers
    /opt/conda/include/python3.8/apex Check the logs for full command
    output.
    The command '/bin/sh -c /tmp/det_dockerfile_scripts/install_apex.sh'
    returned a non-zero code: 1
    Makefile:229: recipe for target 'build-tf2-gpu' failed
```
    This error also occurs when I try building on the current slurm-images
    branch without any of the changes from this PR.

### CODE REVIEW

**Review by stoksc — APPROVED** [review]
lgtm. i will try to debug apex install in time. @ioga may have more thoughts there than me, though, right off.

**Comment by ioga** [comment]
what's in the apex failure logs?

**Comment by stoksc** [comment]
i think it's the error log in the description.

**Comment by cdrickett** [comment]
> hmm, I don't see it? I see the log about pip install in install_apex.sh failure with code 1, but typically there's a ton of build log output prior to it which has the details.

My latest build of the tf2-gpu target succeeded. I think that the install_apex.sh was failing due to system related issues on my side that are a side effect of the size of the docker image being built.

**Pull request merged**
